allowBuilds:
  '@parcel/watcher': set this to true or false
  '@vue-office/docx': set this to true or false
  '@vue-office/excel': set this to true or false
  '@vue-office/pdf': set this to true or false
  '@vue-office/pptx': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false
  '@centrogeomx/sisdai-mapas': true
